plugins:
  - serverless-plugin-typescript
  - serverless-offline

service: nativesamples

provider:
  name: aws
  region: us-east-1
  runtime: nodejs10.x
  stage: prod

functions:
  api:
    handler: src/main.run
    events:
      - http:
          path: /docs
          method: get
          private: false